# Generated by Django 2.2.5 on 2021-05-25 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='first_app.Webpage')),
            ],
        ),
        migrations.DeleteModel(
            name='Acess',
        ),
    ]
